name: Daily News Scraper

on:
  workflow_dispatch: # 수동 실행을 위한 버튼
  schedule:
    # 매일 오전 7시 KST (UTC 22시)에 실행
    - cron: '0 22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas openpyxl

    - name: Run script
      env:
        GNEWS_API_KEY: ${{ secrets.GNEWS_API_KEY }}
        GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      run: python monitor.py

        echo "API_KEY = \"${GNEWS_API_KEY}\"" >> monitor.py
        echo "GMAIL_ADDRESS = \"${GMAIL_ADDRESS}\"" >> monitor.py
        echo "GMAIL_APP_PASSWORD = \"${GMAIL_APP_PASSWORD}\"" >> monitor.py
        # 실제 파이썬 스크립트 실행
        python monitor.py
